move.hold("d",3)
move.hold("s",4)
pag.keyDown("a")
time.sleep(12*29/ws)
pag.keyUp("a")
move.hold("w",3.5)
move.hold("a",0.2)
move.hold("w",6)
move.hold("d",4)
move.hold("s",1)
move.hold("w",2.3)
move.press("space")
time.sleep(0.1)
move.press("space")
time.sleep(8)
move.hold("w",6)
move.hold("s",0.4)
move.hold("d",5)
move.hold("w",1)
move.hold("s",0.55)

    
